POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}


###


GET http://localhost:8000/products/964b4de7-4198-4e8a-9bac-7ece069aef72
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDQ5MTQzMTAsInN1YiI6IjE4Y2E5MjFlLTBlMjQtNGU4Yi04NTA1LTkxYWUyNWVmZjAxZiJ9.TjhkpDq_UHfOvLMHt458JUEeB92ryU8zROFzlsBSIhA


###


PUT http://localhost:8000/products/964b4de7-4198-4e8a-9bac-7ece069aef72
Content-Type: application/json

{
    "name": "My Product V2",
    "price": 150
}


###


DELETE  http://localhost:8000/products/0c40ce1d-3592-4486-a0d8-f8d06c2a4db9	


###



GET http://localhost:8000/products?limit=6&page=1&sort=desc
